# Generated by Django 4.2.5 on 2023-09-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseCode', models.CharField(max_length=20)),
                ('CreditHours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DegreeChecklistTemplate',
            fields=[
                ('TemplateID', models.AutoField(primary_key=True, serialize=False)),
                ('TemplateName', models.CharField(max_length=100)),
                ('AcademicYear', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('ProgramID', models.AutoField(primary_key=True, serialize=False)),
                ('ProgramName', models.CharField(max_length=100)),
                ('ProgramCode', models.CharField(max_length=20)),
                ('TotalCredits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('ContactInfo', models.CharField(max_length=255)),
                ('EnrollmentYear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDegreeChecklist',
            fields=[
                ('ChecklistID', models.AutoField(
                    primary_key=True, serialize=False)),
                ('ChecklistName', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=20)),
                ('Student', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.student')),
                ('Template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='degree_checklist.degreechecklisttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='degreechecklisttemplate',
            name='DegreeProgram',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degreeprogram'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('EnrollmentID', models.AutoField(
                    primary_key=True, serialize=False)),
                ('EnrollmentStatus', models.CharField(max_length=20)),
                ('Course', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.course')),
                ('Student', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.student')),
            ],
        ),
    ]
