# Generated by Django 4.2.5 on 2023-10-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='EnrollmentStatus',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=20),
        ),
    ]
